name: Execute Tests
on:
  push:
    branches: [ main, dev ]
  pull request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test