name: Execute Tests and Deploy
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies and Run Tests for Backend
        run: |
          cd backend-nest
          npm install
          npm test

#      - name: Install Dependencies and Run Tests for Frontend
#        run: |
#          cd frontend-react
#          npm install
#          npm test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy Backend to Dev Server
        run: |
          ssh julesartaud@julesartaud.alwaysdata.net 'cd /www/back-3il-web/backend-nest && git pull && npm ci && npm run build'

#      - name: Deploy Frontend to Dev Server
#        run: |
#          ssh julesartaud@julesartaud.alwaysdata.net 'cd /www/back-3il-web/frontend-react && git pull && npm ci && npm run build'